name: 'Get Arm Toolchain'
description: 'Installs Arm Toolchain'
author: 'TurtleSec'
outputs:
  version:
    description: "The version of Arm Toolchain which was installed"
    value: ${{ steps.output_version.outputs.version }}
  install_dir:
    description: "The path to where the Arm Toolchain was installed"
    value: ${{ steps.output_install_dir.outputs.install_dir }}
runs:
  using: "composite"
  steps:
    - name: Install on Mac/Linux/Windows
      shell: bash
      working-directory: $GITHUB_ACTION_PATH
      run: bash ubuntu.sh || bash macos.sh || powershell windows.ps1

    - name: Fill in install_dir output variable
      id: output_install_dir
      shell: bash
      run: echo "::set-output name=install_dir::$(echo $INSTALL_DIR)"

    - name: Fill in version output variable
      id: output_version
      shell: bash
      run: echo "::set-output name=version::$(arm-none-eabi-gcc --version)"

branding:
  icon: "archive"
  color: "green"
