name: 'Get Arm Toolchain'
description: 'Installs Arm Toolchain'
author: 'TurtleSec'
outputs:
  version:
    description: "The version of Arm Toolchain which was installed"
    value: ${{ steps.output_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install on Mac/Linux/Windows
      shell: bash
      run: bash $GITHUB_ACTION_PATH/ubuntu.sh || bash $GITHUB_ACTION_PATH/macos.sh || powershell $GITHUB_ACTION_PATH/windows.ps1

    - name: Where is it
      shell: bash
      run: dirname `which arm-none-eabi-gcc` #which arm-none-eabi-gcc

    - name: Fill in install_dir output variable
      id: output_install_dir
      shell: bash
      run: |
        INSTALL_DIR=$(dirname `which arm-none-eabi-gcc`)
        echo "::set-output name=install_dir::$(echo $INSTALL_DIR)"

    - name: Fill in version output variable
      id: output_version
      shell: bash
      run: |
        arm-none-eabi-gcc --version
        echo "::set-output name=version::$(arm-none-eabi-gcc --version)"

branding:
  icon: "archive"
  color: "green"
