name: 'Get Arm Toolchain'
description: 'Installs Arm Toolchain'
author: 'TurtleSec'
outputs:
  version:
    description: "The version of Arm Toolchain which was installed"
    value: ${{ steps.output_version.outputs.version }}
  install_dir:
    description: "The path to where the Arm Toolchain was installed"
    value: ${{ steps.output_install_dir.outputs.install_dir }}
runs:
  using: "composite"
  steps:
    - name: Install on Mac/Linux/Windows
      shell: bash
      run: bash $GITHUB_ACTION_PATH/ubuntu.sh || bash $GITHUB_ACTION_PATH/macos.sh || powershell $GITHUB_ACTION_PATH/windows.ps1

    - name: Fill in install_dir output variable
      id: output_install_dir
      shell: bash
      run: |
        echo $INSTALL_DIR
        echo "install_dir=$INSTALL_DIR" >> $GITHUB_OUTPUT

    - name: Fill in version output variable
      id: output_version
      shell: bash
      run: |
        arm-none-eabi-gcc --version
        echo "VERSION=$(arm-none-eabi-gcc --version)" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

branding:
  icon: "archive"
  color: "green"
