name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conf:
          - name: Windows 2019
            os: windows-2019
            host_executable_suffix: ".exe"
          - name: Ubuntu 20.04
            os: ubuntu-20.04
            host_executable_suffix: ""
          - name: Ubuntu 18.04
            os: ubuntu-18.04
            host_executable_suffix: ""
          - name: MacOS 10.15
            os: macos-10.15
            host_executable_suffix: ""

    runs-on: ${{ matrix.conf.os }}
    name: "${{ matrix.conf.name }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Arm Toolchain
        id: arm
        uses: ./ # Uses an action in the root directory

      - name: Did we get Arm Toolchain?
        run: echo "Arm Toolchain version was '${{ steps.arm.outputs.version }}'"

      - name: Where is the Arm Toolchain?
        run: echo "Arm Toolchain is at '${{ steps.arm.outputs.install_dir }}'"

      - name: Test the Arm Toolchain
        shell: bash
        working-directory: "${{ steps.arm.outputs.install_dir }}"
        run: ./arm-none-eabi-gcc${{ matrix.conf.host_executable_suffix}} --version
