name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Arm Toolchain
        id: arm
        uses: ./ # Uses an action in the root directory

      - name: Did we get Arm Toolchain?
        run: echo "Arm Toolchain version was '${{ steps.arm.outputs.version }}'"
